#!/bin/bash

#echo "ARGS: " $*

if [ -z "$*" ]; then
  FPATH='"."'
else

  FPATH=`wslpath -w "$1"`
  FPATH=\"$FPATH\"
  FNAME=$(basename "$1")
  ext="${FNAME##*.}"
  if [ -n "$ext" ]; then
    ext="$(printf "%s" "${ext}" | tr '[:upper:]' '[:lower:]')"
  fi
fi

shift
if [ -n "$*" ]; then
  poshargs="-ArgumentList \""$*"\""
  #echo $poshargs
fi

#adapted from https://superuser.com/questions/1160419/how-can-i-open-a-file-from-wsl-with-the-default-application
case "${ext}" in
    cmd|bat)
      #powershell.exe -Command Start-Process "`wslpath -w "$FPATH"`" -NoNewWindow $poshargs
      cmd.exe /c "`wslpath -w "$FPATH"`"
      ;;
    *)

      #powershell.exe -Command Start-Process "`wslpath -w "$FPATH"`" $poshargs
      powershell.exe -Command Start-Process $FPATH $poshargsq
      ;;
esac
