#!/bin/zsh

if [ "$1" = "sel-cmd" ]; then
  cmd_vs="Open in VSCode"
  cmd_copy_clip="Copy to win clipboard"
  cmd=$(echo "$cmd_vs\n$cmd_copy_clip" | fzf )
  echo $cmd
  exit
fi


pwsh='/mnt/c/Program Files/PowerShell/7-preview/pwsh.exe'
vscode='C:\Users\oleg\AppData\Local\Programs\Microsoft VS Code\Code.exe'

ps_launch() {
	name=$1
	gui=$2
	shift 2
    if [ -z "$*" ]; then
      arglist=""
    else
      arglist=("-ArgumentList" "\"${(j:",":)*}\"")
    fi  
    #echo ${arglist}
    #printf "ps_launch: opening %s\n" "$name"
    #printf "ps_launch: gui mode=%s\n" "$gui"
    if [ $gui = true ]; then
    	$pwsh -Command Start-Process "\"${name}\"" ${arglist}
    else
    	$pwsh -Command Start-Process "\"${name}\"" -NoNewWindow ${arglist} -Wait
    fi	
}

#if no parameters given then open current folder in explorer
if [ -z "$*" ]; then
  #$pwsh -Command Start-Process "."
  ps_launch "." true
  exit
fi

if [ "$1" = "code" ]; then
  ps_launch "$vscode" true "."
  exit
fi

if [ "$1" = ">clip" ]; then
  ps_launch "clip.exe" true ""
  exit
fi

gui_flag=false

if [ "$1" = "--gui" ]; then
  gui_flag=true
  shift
fi



fullpath="$1"
#printf "%s" "$fullpath"
winpath=$(wslpath -w "$1" 2> /dev/null || printf "%s" "$1")
#printf "%s" "$winpath"
filename="${fullpath##*/}"
extension="${fullpath##*.}"
#incompatible with bash, zsh-specific
extension="${extension:l}"

shift

#adapted from https://superuser.com/questions/1160419/how-can-i-open-a-file-from-wsl-with-the-default-application
case "$extension" in
    cmd|bat)
      #using "printf" because fucking "echo" treats sequences like "\t" in the output as escape sequences
      #printf '%s\n' "$winpath" 
      #cmd.exe /c "$winpath" "$@"
      ps_launch cmd.exe false /c "$winpath" "$@"
      ;;
    doc|docx|xls|xlsx|pdf|jpg|jpeg|png|sql|exe)
      #echo ${poshargs}
      #$pwsh -Command Start-Process "\"$winpath\"" -NoNewWindow ${(j:",":)poshargs} -Wait
      ps_launch "$winpath" "$gui_flag" $*
      ;;
    *)
      if [[ "$fullpath" =~ ^[^/]*$ ]]; then
        ( "./$fullpath" "$@")
      else
        ( "$fullpath" "$@") 
      fi
      ;;
esac

